[package]
name = "MonochromeImageToSVGConverter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
image = "0.23"
imageproc = "0.22"
svg = "0.10"
indicatif = "0.16"
